// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package crdb

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Feedbacks", testFeedbacksUpsert)
	t.Run("FeedbackComments", testFeedbackCommentsUpsert)
	t.Run("UserAccounts", testUserAccountsUpsert)
}
