// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package crdb

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/randomize"
	"github.com/volatiletech/sqlboiler/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testFeedbacks(t *testing.T) {
	t.Parallel()

	query := Feedbacks()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testFeedbacksDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Feedbacks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFeedbacksQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Feedbacks().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Feedbacks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFeedbacksSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FeedbackSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Feedbacks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testFeedbacksExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := FeedbackExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Feedback exists: %s", err)
	}
	if !e {
		t.Errorf("Expected FeedbackExists to return true, but got false.")
	}
}

func testFeedbacksFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	feedbackFound, err := FindFeedback(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if feedbackFound == nil {
		t.Error("want a record, got nil")
	}
}

func testFeedbacksBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Feedbacks().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testFeedbacksOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Feedbacks().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testFeedbacksAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	feedbackOne := &Feedback{}
	feedbackTwo := &Feedback{}
	if err = randomize.Struct(seed, feedbackOne, feedbackDBTypes, false, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}
	if err = randomize.Struct(seed, feedbackTwo, feedbackDBTypes, false, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = feedbackOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = feedbackTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Feedbacks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testFeedbacksCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	feedbackOne := &Feedback{}
	feedbackTwo := &Feedback{}
	if err = randomize.Struct(seed, feedbackOne, feedbackDBTypes, false, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}
	if err = randomize.Struct(seed, feedbackTwo, feedbackDBTypes, false, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = feedbackOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = feedbackTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Feedbacks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func feedbackBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Feedback) error {
	*o = Feedback{}
	return nil
}

func feedbackAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Feedback) error {
	*o = Feedback{}
	return nil
}

func feedbackAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Feedback) error {
	*o = Feedback{}
	return nil
}

func feedbackBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Feedback) error {
	*o = Feedback{}
	return nil
}

func feedbackAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Feedback) error {
	*o = Feedback{}
	return nil
}

func feedbackBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Feedback) error {
	*o = Feedback{}
	return nil
}

func feedbackAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Feedback) error {
	*o = Feedback{}
	return nil
}

func feedbackBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Feedback) error {
	*o = Feedback{}
	return nil
}

func feedbackAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Feedback) error {
	*o = Feedback{}
	return nil
}

func testFeedbacksHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Feedback{}
	o := &Feedback{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, feedbackDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Feedback object: %s", err)
	}

	AddFeedbackHook(boil.BeforeInsertHook, feedbackBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	feedbackBeforeInsertHooks = []FeedbackHook{}

	AddFeedbackHook(boil.AfterInsertHook, feedbackAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	feedbackAfterInsertHooks = []FeedbackHook{}

	AddFeedbackHook(boil.AfterSelectHook, feedbackAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	feedbackAfterSelectHooks = []FeedbackHook{}

	AddFeedbackHook(boil.BeforeUpdateHook, feedbackBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	feedbackBeforeUpdateHooks = []FeedbackHook{}

	AddFeedbackHook(boil.AfterUpdateHook, feedbackAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	feedbackAfterUpdateHooks = []FeedbackHook{}

	AddFeedbackHook(boil.BeforeDeleteHook, feedbackBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	feedbackBeforeDeleteHooks = []FeedbackHook{}

	AddFeedbackHook(boil.AfterDeleteHook, feedbackAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	feedbackAfterDeleteHooks = []FeedbackHook{}

	AddFeedbackHook(boil.BeforeUpsertHook, feedbackBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	feedbackBeforeUpsertHooks = []FeedbackHook{}

	AddFeedbackHook(boil.AfterUpsertHook, feedbackAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	feedbackAfterUpsertHooks = []FeedbackHook{}
}

func testFeedbacksInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Feedbacks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFeedbacksInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(feedbackColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Feedbacks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testFeedbackToManyFeedbackComments(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Feedback
	var b, c FeedbackComment

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, feedbackCommentDBTypes, false, feedbackCommentColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, feedbackCommentDBTypes, false, feedbackCommentColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.FeedbackID = a.ID
	c.FeedbackID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.FeedbackComments().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.FeedbackID == b.FeedbackID {
			bFound = true
		}
		if v.FeedbackID == c.FeedbackID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := FeedbackSlice{&a}
	if err = a.L.LoadFeedbackComments(ctx, tx, false, (*[]*Feedback)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FeedbackComments); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.FeedbackComments = nil
	if err = a.L.LoadFeedbackComments(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.FeedbackComments); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testFeedbackToManyAddOpFeedbackComments(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Feedback
	var b, c, d, e FeedbackComment

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, feedbackDBTypes, false, strmangle.SetComplement(feedbackPrimaryKeyColumns, feedbackColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*FeedbackComment{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, feedbackCommentDBTypes, false, strmangle.SetComplement(feedbackCommentPrimaryKeyColumns, feedbackCommentColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*FeedbackComment{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddFeedbackComments(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.FeedbackID {
			t.Error("foreign key was wrong value", a.ID, first.FeedbackID)
		}
		if a.ID != second.FeedbackID {
			t.Error("foreign key was wrong value", a.ID, second.FeedbackID)
		}

		if first.R.Feedback != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Feedback != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.FeedbackComments[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.FeedbackComments[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.FeedbackComments().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testFeedbacksReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFeedbacksReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := FeedbackSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testFeedbacksSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Feedbacks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	feedbackDBTypes = map[string]string{`AgeSuitability`: `int8`, `CreatedAt`: `timestamptz`, `FeedbackTypeID`: `int8`, `ID`: `int8`, `Title`: `varchar`, `Text`: `varchar`, `UserAccountID`: `int8`}
	_               = bytes.MinRead
)

func testFeedbacksUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(feedbackPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(feedbackAllColumns) == len(feedbackPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Feedbacks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testFeedbacksSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(feedbackAllColumns) == len(feedbackPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Feedback{}
	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Feedbacks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, feedbackDBTypes, true, feedbackPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(feedbackAllColumns, feedbackPrimaryKeyColumns) {
		fields = feedbackAllColumns
	} else {
		fields = strmangle.SetComplement(
			feedbackAllColumns,
			feedbackPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := FeedbackSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testFeedbacksUpsert(t *testing.T) {
	t.Parallel()

	if len(feedbackAllColumns) == len(feedbackPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Feedback{}
	if err = randomize.Struct(seed, &o, feedbackDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Feedback: %s", err)
	}

	count, err := Feedbacks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, feedbackDBTypes, false, feedbackPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Feedback struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Feedback: %s", err)
	}

	count, err = Feedbacks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
